=== 1989076090/ismrmrd/schema/ismrmrd.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://www.ismrm.org/ISMRMRD" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.ismrm.org/ISMRMRD">

  <xs:element name="ismrmrdHeader">
    <xs:complexType>
      <xs:sequence>
	<xs:element maxOccurs="1" minOccurs="0" name="subjectInformation" type="subjectInformationType"/>
	<xs:element maxOccurs="1" minOccurs="0" name="acquisitionSystemInformation" type="acquisitionSystemInformationType"/>
	<xs:element maxOccurs="1" minOccurs="1" name="experimentalConditions" type="experimentalConditionsType"/>
	<xs:element maxOccurs="unbounded" minOccurs="1" name="encoding">
	  <xs:complexType>
	    <xs:all>
	      <xs:element maxOccurs="1" minOccurs="1" name="encodedSpace" type="encodingSpaceType"/>
	      <xs:element maxOccurs="1" minOccurs="1" name="reconSpace" type="encodingSpaceType"/>
	      <xs:element maxOccurs="1" minOccurs="1" name="encodingLimits" type="encodingLimitsType"/>
	      <xs:element maxOccurs="1" minOccurs="1" name="trajectory" type="trajectoryType"/>
	      <xs:element maxOccurs="1" minOccurs="0" name="trajectoryDescription" type="trajectoryDescriptionType"/>
	    </xs:all>
	  </xs:complexType>
	</xs:element>
	<xs:element maxOccurs="1" minOccurs="0" name="parallelImaging" type="parallelImagingType"/>
	<xs:element maxOccurs="1" minOccurs="0" name="sequenceTiming" type="sequenceTimingType"/>
        <xs:element maxOccurs="1" minOccurs="0" name="dicomParameters" type="dicomParametersType"/>
	<xs:element maxOccurs="1" minOccurs="0" name="userParameters">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element maxOccurs="unbounded" minOccurs="0" name="userParameterLong" type="userParameterLongType"/>
	      <xs:element maxOccurs="unbounded" minOccurs="0" name="userParameterDouble" type="userParameterDoubleType"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="subjectInformationType">
    <xs:all>
      <xs:element minOccurs="0" name="patientName" type="xs:string"/>
      <xs:element minOccurs="0" name="patientWeight_kg" type="xs:float"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="experimentalConditionsType">
    <xs:all>
      <xs:element name="H1resonanceFrequency_Hz" type="xs:long"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="acquisitionSystemInformationType">
    <xs:all>
      <xs:element minOccurs="0" name="systemVendor" type="xs:string"/>
      <xs:element minOccurs="0" name="systemModel" type="xs:string"/>
      <xs:element minOccurs="0" name="systemFieldStrength_T" type="xs:float"/>
      <xs:element minOccurs="0" name="relativeReceiverNoiseBandwidth" type="xs:float"/>
      <xs:element minOccurs="0" name="receiverChannels" type="xs:unsignedShort"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="encodingSpaceType">
    <xs:all>
      <xs:element name="matrixSize">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element default="1" maxOccurs="1" minOccurs="1" name="x" type="xs:unsignedShort"/>
	    <xs:element default="1" maxOccurs="1" minOccurs="1" name="y" type="xs:unsignedShort"/>
	    <xs:element default="1" maxOccurs="1" minOccurs="1" name="z" type="xs:unsignedShort"/>
	  </xs:sequence>
	</xs:complexType>
      </xs:element>
      <xs:element name="fieldOfView_mm">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element maxOccurs="1" minOccurs="1" name="x" type="xs:float"/>
	    <xs:element maxOccurs="1" minOccurs="1" name="y" type="xs:float"/>
	    <xs:element maxOccurs="1" minOccurs="1" name="z" type="xs:float"/>
	  </xs:sequence>
	</xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="limitType">
    <xs:all>
      <xs:element default="0" name="minimum" type="xs:unsignedShort"/>
      <xs:element default="0" name="maximum" type="xs:unsignedShort"/>
      <xs:element default="0" name="center" type="xs:unsignedShort"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="encodingLimitsType">
    <xs:all>
      <xs:element maxOccurs="1" minOccurs="0" name="kspace_encoding_step_0" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="kspace_encoding_step_1" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="kspace_encoding_step_2" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="average" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="slice" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="contrast" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="phase" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="repetition" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="set" type="limitType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="segment" type="limitType"/>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="trajectoryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cartesian"/>
      <xs:enumeration value="epi"/>
      <xs:enumeration value="radial"/>
      <xs:enumeration value="goldenangle"/>
      <xs:enumeration value="spiral"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="trajectoryDescriptionType">
    <xs:sequence>
      <xs:element maxOccurs="1" minOccurs="1" name="identifier" type="xs:string"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="userParameterLong" type="userParameterLongType"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="userParameterDouble" type="userParameterDoubleType"/>
      <xs:element maxOccurs="1" minOccurs="0" name="comment" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sequenceTimingType">
  	<xs:sequence>
  		<xs:element minOccurs="1" maxOccurs="unbounded" type="xs:float" name="TR"/>
  		<xs:element minOccurs="1" maxOccurs="unbounded" type="xs:float" name="TE"/>
  		<xs:element minOccurs="0" maxOccurs="unbounded" type="xs:float" name="TI"/>
  	</xs:sequence>
  </xs:complexType>

  <xs:complexType name="userParameterLongType">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="value" type="xs:long"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="userParameterDoubleType">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="value" type="xs:double"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="dicomParametersType">
    <xs:all>
      <xs:element minOccurs="1" maxOccurs="1" name="dicomPatient">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="patientID"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="patientBirthdate"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="patientSex"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="patientAge_y"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="dicomStudy">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="0" maxOccurs="1" name="referencedImageSequence">
              <xs:complexType>
                <xs:sequence>
                  <xs:element minOccurs="0" maxOccurs="unbounded" type="xs:string" name="referencedSOPInstanceUID"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="studyInstanceUID"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="studyID"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="studyDate"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="studyTime"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="referringPhysicianName"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="accessionNumber"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="studyDescription"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="dicomSeries">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="seriesInstanceUID"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="seriesNumber"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="seriesDate"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="seriesTime"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="protocolName"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="seriesDescription"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="patientPosition"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="frameOfReferenceUID"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="dicomMRImage">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="imageType"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="scanningSequence"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="sequenceVariant"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="scanOptions"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="mrAcquisitionType"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="echoTrainLength"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:float" name="triggerTime"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:long" name="flipAngle_deg"/>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="freqEncodingDirection"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="dicomGeneralEquipment">
        <xs:complexType>
          <xs:all>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="institutionName"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="stationName"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="accelerationFactorType">
    <xs:all>
      <xs:element name="kspace_encoding_step_1" type="xs:unsignedShort"/>
      <xs:element name="kspace_encoding_step_2" type="xs:unsignedShort"/>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="calibrationModeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="embedded"/>
      <xs:enumeration value="interleaved"/>
      <xs:enumeration value="separate"/>
      <xs:enumeration value="external"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="interleavingDimensionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="phase"/>
      <xs:enumeration value="repetition"/>
      <xs:enumeration value="contrast"/>
      <xs:enumeration value="average"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="parallelImagingType">
  	<xs:sequence>
  	 <xs:element type="accelerationFactorType" name="accelerationFactor"/>
  	 <xs:element maxOccurs="1" minOccurs="0" type="calibrationModeType" name="calibrationMode"/>
  	 <xs:element maxOccurs="1" minOccurs="0" type="interleavingDimensionType" name="interleavingDimension"/>
  	</xs:sequence>
  </xs:complexType>
</xs:schema>

=== 1989076090/ismrmrd/schema/ismrmrd_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ismrmrdHeader xsi:schemaLocation="http://www.ismrm.org/ISMRMRD ismrmrd.xsd"
        xmlns="http://www.ismrm.org/ISMRMRD"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <subjectInformation>
    <patientName>Anonymous</patientName>
    <patientWeight_kg>74.7</patientWeight_kg>
  </subjectInformation>

  <acquisitionSystemInformation>
    <systemVendor>Siemens</systemVendor>
    <systemModel>Avanto</systemModel>
    <systemFieldStrength_T>1.5</systemFieldStrength_T>
  </acquisitionSystemInformation>

  <experimentalConditions>
    <H1resonanceFrequencyHz>63500000</H1resonanceFrequencyHz>
  </experimentalConditions>

  <encoding>
    <trajectory>cartesian</trajectory>
    <encodingLimits>
      <kspace_encoding_step_1>
        <minimum>0</minimum>
        <maximum>96</maximum>
        <center>48</center>
      </kspace_encoding_step_1>
    </encodingLimits>

    <encodedSpace>
      <matrixSize>
        <x>256</x>
        <y>96</y>
        <z>1</z>
      </matrixSize>
      <fieldOfView_m>
        <x>0.600</x>
        <y>0.230</y>
        <z>0.006</z>
      </fieldOfView_m>
    </encodedSpace>

    <reconSpace>
      <matrixSize>
        <x>128</x>
        <y>96</y>
        <z>1</z>
      </matrixSize>

      <fieldOfView_m>
        <x>0.300</x>
        <y>0.230</y>
        <z>0.006</z>
      </fieldOfView_m>
    </reconSpace>
  </encoding>

  <userParameters>
    <userParameterLong>
      <name>MySpecialParameter1</name>
      <value>724873268</value>
    </userParameterLong>

    <userParameterLong>
      <name>AnotherSpecialParameter</name>
      <value>19238719</value>
    </userParameterLong>

    <userParameterDouble>
      <name>ADoubleParameter</name>
      <value>76238.878437</value>
    </userParameterDouble>
  </userParameters>
</ismrmrdHeader>

=== 1989076090/ismrmrd/schema/ismrmrd_example_extended.xml
<?xml version="1.0"?>
<ismrmrdHeader xmlns="http://www.ismrm.org/ISMRMRD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.ismrm.org/ISMRMRD ismrmrd.xsd">
  <subjectInformation>
    <patientName>Anonymous Patient</patientName>
    <patientWeight_kg>70.3068</patientWeight_kg>
    <patientID>BHHG8866789</patientID>
    <patientBirthdate>1980-06-12</patientBirthdate>
    <patientGender>M</patientGender>
  </subjectInformation>
  <studyInformation>
    <studyDate>2012-08-13</studyDate>
    <studyTime>09:00:00</studyTime>
    <studyID>NNLLJHG88997</studyID>
    <accessionNumber>7638376482</accessionNumber>
    <referringPhysicianName>John Doe, MD</referringPhysicianName>
    <studyDescription>This is an example study with all headers set</studyDescription>
  </studyInformation>
  <measurementInformation>
    <measurementID>LLJGHH888986</measurementID>
    <seriesDate>2012-08-13</seriesDate>
    <seriesTime>09:10:12</seriesTime>
    <patientPosition>HFS</patientPosition>
    <initialSeriesNumber>1</initialSeriesNumber>
    <protocolName>ExampleProt</protocolName>
    <seriesDescription>MRIStudy1</seriesDescription>
    <measurementDependency>
      <dependencyType>Noise</dependencyType>
      <measurementID>HHJJHJL000977889</measurementID>
    </measurementDependency>
    <measurementDependency>
      <dependencyType>SurfaceCoilCorrection</dependencyType>
      <measurementID>HHJJHJL000977810</measurementID>
    </measurementDependency>
  </measurementInformation>
  <acquisitionSystemInformation>
    <systemVendor>SIEMENS</systemVendor>
    <systemModel>Avanto</systemModel>
    <systemFieldStrength_T>1.494</systemFieldStrength_T>
    <relativeReceiverNoiseBandwidth>0.79</relativeReceiverNoiseBandwidth>
    <receiverChannels>32</receiverChannels>
    <institutionName>Some University</institutionName>
    <stationName>MRI Scanner 1</stationName>
  </acquisitionSystemInformation>
  <experimentalConditions>
    <H1resonanceFrequency_Hz>63642459</H1resonanceFrequency_Hz>
  </experimentalConditions>
  <encoding>
    <encodedSpace>
      <matrixSize>
        <x>256</x>
        <y>140</y>
        <z>80</z>
      </matrixSize>
      <fieldOfView_mm>
        <x>600</x>
        <y>328.153125</y>
        <z>160</z>
      </fieldOfView_mm>
    </encodedSpace>
    <reconSpace>
      <matrixSize>
        <x>128</x>
        <y>116</y>
        <z>64</z>
      </matrixSize>
      <fieldOfView_mm>
        <x>300</x>
        <y>271.875</y>
        <z>128</z>
      </fieldOfView_mm>
    </reconSpace>
    <encodingLimits>
      <kspace_encoding_step_1>
        <minimum>0</minimum>
        <maximum>83</maximum>
        <center>28</center>
      </kspace_encoding_step_1>
      <kspace_encoding_step_2>
        <minimum>0</minimum>
        <maximum>45</maximum>
        <center>20</center>
      </kspace_encoding_step_2>
      <slice>
        <minimum>0</minimum>
        <maximum>0</maximum>
        <center>0</center>
      </slice>
      <set>
        <minimum>0</minimum>
        <maximum>0</maximum>
        <center>0</center>
      </set>
    </encodingLimits>
    <trajectory>cartesian</trajectory>
  </encoding>
  <encoding>
    <encodedSpace>
      <matrixSize>
        <x>64</x>
        <y>64</y>
        <z>64</z>
      </matrixSize>
      <fieldOfView_mm>
        <x>300</x>
        <y>300</y>
        <z>300</z>
      </fieldOfView_mm>
    </encodedSpace>
    <reconSpace>
      <matrixSize>
        <x>64</x>
        <y>64</y>
        <z>64</z>
      </matrixSize>
      <fieldOfView_mm>
        <x>300</x>
        <y>300</y>
        <z>300</z>
      </fieldOfView_mm>
    </reconSpace>
    <encodingLimits>
      <kspace_encoding_step_1>
        <minimum>0</minimum>
        <maximum>8</maximum>
        <center>0</center>
      </kspace_encoding_step_1>
      <kspace_encoding_step_2>
        <minimum>0</minimum>
        <maximum>16</maximum>
        <center>0</center>
      </kspace_encoding_step_2>
      <average>
        <minimum>0</minimum>
        <maximum>16</maximum>
        <center>0</center>	
      </average>
      <slice>
        <minimum>0</minimum>
        <maximum>0</maximum>
        <center>0</center>
      </slice>
      <contrast>
        <minimum>2</minimum>
        <maximum>4</maximum>
        <center>3</center>	
      </contrast>
      <phase>
        <minimum>0</minimum>
        <maximum>0</maximum>
        <center>0</center>	
      </phase>
      <repetition>
	<minimum>0</minimum>
        <maximum>16</maximum>
        <center>8</center>	
      </repetition>
      <set>
        <minimum>0</minimum>
        <maximum>0</maximum>
        <center>0</center>
      </set>
      <segment>
        <minimum>0</minimum>
        <maximum>1</maximum>
        <center>0</center>	
      </segment>
    </encodingLimits>
    <trajectory>other</trajectory>
    <trajectoryDescription>
      <identifier>Custom Trajector</identifier>
      <userParameterLong>
	<name>sample_rate_ns</name>
	<value>100</value>
      </userParameterLong>
      <userParameterLong>
	<name>constant_1</name>
	<value>300</value>
      </userParameterLong>
      <userParameterDouble>
	<name>coefficient_1</name>
	<value>2.72386</value>
      </userParameterDouble>
      <userParameterDouble>
	<name>coefficient_2</name>
	<value>2233.72</value>
      </userParameterDouble>
      <userParameterDouble>
	<name>coefficient_3</name>
	<value>112.86</value>
      </userParameterDouble>
      <comment>This is an example description of a custom trajectory</comment>
    </trajectoryDescription>
  </encoding>
  <parallelImaging>
    <accelerationFactor>
      <kspace_encoding_step_1>1</kspace_encoding_step_1>
      <kspace_encoding_step_2>2</kspace_encoding_step_2>
    </accelerationFactor>
    <calibrationMode>other</calibrationMode>
  </parallelImaging>
  <sequenceParameters>
    <TR>4.6</TR>
    <TE>2.35</TE>
    <TE>4.35</TE>
    <TE>6.55</TE>
    <TE>9.22</TE>
    <TI>300.08</TI>
  </sequenceParameters>
  <dicomParameters>
    <studyInstanceUID>1.34.896.2789852.787873.9999</studyInstanceUID>
    <seriesInstanceUIDRoot>1.34.896.2789852.787873</seriesInstanceUIDRoot>
    <frameOfReferenceUID>1.34.896.2789852.787873.98788.78787</frameOfReferenceUID>
    <referencedImageSequence>
      <referencedSOPInstanceUID>1.34.896.2789852.787873.98788.78787.1</referencedSOPInstanceUID>
      <referencedSOPInstanceUID>1.34.896.2789852.787873.98788.78787.2</referencedSOPInstanceUID>
      <referencedSOPInstanceUID>1.34.896.2789852.787873.98788.78787.3</referencedSOPInstanceUID>
      <referencedSOPInstanceUID>1.34.896.2789852.787873.98788.78787.4</referencedSOPInstanceUID>
    </referencedImageSequence>
    <MRImageModule>
      <imageType>MAGNITUDE</imageType>
      <scanningSequence>TSE</scanningSequence>
      <sequenceVariant>HASTE</sequenceVariant>
      <scanOptions>Pre-ON</scanOptions>
      <mrAcquisitionType>SE</mrAcquisitionType>
      <echoTrainLength>12</echoTrainLength>
      <triggerTime>100.212</triggerTime>
      <flipAngle_deg>90.0</flipAngle_deg>
      <freqEncodingDirection>ROW</freqEncodingDirection>
    </MRImageModule>
  </dicomParameters>
  <userParameters>
    <userParameterLong>
      <name>dev_long_1</name>
      <value>789</value>
    </userParameterLong>
    <userParameterLong>
      <name>dev_long_2</name>
      <value>999</value>
    </userParameterLong>
    <userParameterDouble>
      <name>dev_double1</name>
      <value>999.999</value>
    </userParameterDouble>
    <userParameterDouble>
      <name>dev_double2</name>
      <value>9.1111</value>
    </userParameterDouble>
    <userParameterString>
      <name>FILTER_SHAPE</name>
      <value>GAUSSIAN</value>
    </userParameterString>
    <userParameterBase64>
      <name>VENDOR_PROTOCOL</name>
      <value>VGhpcyBpcyBhIGpvdXJuZXkgaW50byBzb3VuZA==</value>
    </userParameterBase64>
  </userParameters>
</ismrmrdHeader>
